
class Constants:
    ARGUMENT_PATH = "--iquail_path"
    IQUAIL_TO_UPDATE = "iquail.update.exe"
    IQUAIL_ROOT_NAME = ".iquail"
    ARGUMENT_UNINSTALL = "--iquail_uninstall"
    ARGUMENT_BUILD = "--iquail_build"
    ARGUMENT_RM = "--iquail_rm"
    ARGUMENT_REPLACE = "--iquail_replace"
    ARGUMENT_INSTALL_POLKIT = "--iquail_install_polkit"
    ARGUMENT_RUN = "--iquail_run"
    CHECKSUMS_FILE = ".integrity.json"
    INTEGRITY_IGNORE_FILE = ".integrity_ignore"
    VERSION_FILE = "solution_version.txt"
    CONFIG_FILE = "config.ini"
    PATH_SEP = "::"
